/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 cake.gltf
*/

import React, {useRef} from 'react'
import {useGLTF, useTexture} from '@react-three/drei'
import {useCustomization} from "../contexts/Customization.jsx";
import {Color} from "three";

export function Cake(props) {
    const {nodes, materials} = useGLTF('/cake.gltf')
    const { material, form, cakeColor, creamColor } = useCustomization();
    const stand_color = new Color('#c41313');
    nodes.Mesh004.material.color = stand_color
    nodes.Mesh004_1.material.color = stand_color
    nodes.Mesh004_2.material.color = stand_color
    nodes.Mesh004_3.material.color = stand_color

    const leatherTextureProps = useTexture({
        // map: "./textures/leather/Leather_008_Base Color.jpg",
        normalMap: "./textures/leather/Leather_008_Normal.jpg",
        roughnessMap: "./textures/leather/Leather_008_Roughness.jpg",
        aoMap: "./textures/leather/Leather_008_Ambient Occlusion.jpg",
    });

    return (
        <group {...props} dispose={null}>
            <group rotation={[Math.PI / 2, 0, 0]} scale={0.07}>
                <group position={[0, 0, -27.2]} scale={1.01}>
                    <mesh geometry={nodes.Mesh004.geometry} material={materials['Strip Part']}/>
                    <mesh geometry={nodes.Mesh004_1.geometry} material={materials['Primary Part']}/>
                    <mesh geometry={nodes.Mesh004_2.geometry} material={materials['Add Part M']}/>
                    <mesh geometry={nodes.Mesh004_3.geometry} material={materials.plastic1}/>
                </group>
            </group>
            <mesh geometry={nodes.Cake.geometry} material={materials.Cake} position={[0, 1.89, 0]}
                  scale={[0.95, 0.92, 0.95]}>
                <meshStandardMaterial
                    {...leatherTextureProps}
                    color={'#c86ce5'}
                />
            </mesh>
            <mesh geometry={nodes.cakeHeart.geometry} material={materials.Cake} position={[0, 1.41, 0]}
                  rotation={[1.57, 0, 0]} scale={0.1} visible={false}/>
            <mesh geometry={nodes.cream.geometry} material={materials.Cream} position={[0, 1.41, 0]}
                  rotation={[1.57, 0, 0]} scale={0.1} visible={false}/>
            <mesh geometry={nodes.chandel.geometry} material={materials.chandel} position={[0, 2.33, 0]}
                  rotation={[-Math.PI / 2, 0, 0]} scale={-0.03}/>
            <group position={[0.08, 2.31, 0.42]} rotation={[Math.PI / 2, 0, -2.81]} scale={0.18}>
                <mesh geometry={nodes.Mesh021.geometry} material={materials.Default}/>
                <mesh geometry={nodes.Mesh021_1.geometry} material={materials.Default}/>
            </group>
            <mesh geometry={nodes.bar.geometry} material={materials.choco} position={[0, 2.5, 0]}
                  rotation={[2.87, -0.55, -2.38]} scale={0.1}/>
            <mesh geometry={nodes.balls.geometry} material={materials.balls} position={[0.27, 2.44, -0.05]}
                  rotation={[-2.24, 0.35, -0.42]} scale={-0.06}/>
        </group>
    )
}

useGLTF.preload('/cake.gltf')
